### PR TITLE
Issue 4.ilya.validation errors

### LINKED ISSUE #4: Fail generation in case of validation errors
Show errors in the console

### PR DESCRIPTION
**Pull request by slonia**
Fixes #4 

LemonDocs::Validator.validate! can work in normal and strict (by default) modes. When strict mode is disabled all warnings are ignored, only errors count.

### CODE REVIEW

File: lib/lemon_docs.rb [hunk 1]
```diff
@@ -18,21 +20,26 @@ def self.parse(raw_blueprint)
...
 
   def self.parse_file(file_path)
     file = File.new(file_path)
-    parse(file.read)
+    content = file.read
+    output = parse(content)
+    if LemonDocs::Validator.validate!(output)
+      markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(content)
+      IO.write(file_path.gsub(".md", ".html"), markdown)
+    end
```
Comment (slonia) [inline lib/lemon_docs.rb:42]: [1] pry(main)> require_relative 'lib/lemon_docs'
=> true
[2] pry(main)> LemonDocs.parse_file("/home/berlin/md/test.md")

you will get /home/berlin/md/test.html
